# <!-- Powered by BMAD™ Core -->
# PocketCorn v4.1 BMAD Core Configuration - AI Investment Analysis System
markdownExploder: true
slashPrefix: PocketCorn

# Project Information
project_info:
  name: "PocketCorn v4.1 - AI Investment Analysis System"
  version: "v4.1.0_BMAD"
  description: "基于多信号交叉验证的AI初创企业15%分红投资分析系统"
  core_philosophy: "智能化的关键在于决策节点，而非程序复杂度"
  investment_model: "15% Monthly Revenue Sharing (RBF)"
  target_investment: "¥500,000 per project"
  payback_target: "6-8 months"

# Local Path Configuration (Project-Relative)
paths:
  bmad_core: .claude/bmad-core
  agents: .claude/agents
  commands: .claude/commands
  templates: .claude/bmad-core/templates
  checklists: .claude/bmad-core/checklists
  tasks: .claude/bmad-core/tasks
  data: .claude/bmad-core/data
  workflows: .claude/bmad-core/workflows
  reports: outputs/reports
  discovery_cache: outputs/discovery
  analysis_cache: outputs/analysis

# Claude Code Integration
claude_code:
  subagent_source: .claude/agents
  command_source: .claude/commands
  mcp_integration: enabled
  hook_system: enabled
  primary_agent: po-investment-analyst

# Investment Analysis Configuration
investment_analysis:
  primary_methodology: "Multi-Signal Cross-Validation Discovery"
  scoring_system: "SPELO 7-Dimension Analysis"
  signal_sources: ["twitter", "linkedin", "yc", "funding_news"]
  target_regions: ["China", "US"]
  investment_criteria:
    min_team_size: 3
    max_team_size: 50
    target_stages: ["PMF", "Growth", "Series A"]
    min_mrr_usd: 10000
    revenue_sharing_rate: 0.15

# Multi-Signal Discovery Configuration
discovery:
  signal_sources:
    twitter:
      enabled: true
      keywords: ["AI startup", "人工智能创业", "Series A AI", "AI产品发布"]
      confidence_weight: 0.8
      rate_limit: 100
      cache_ttl: 3600
    linkedin:
      enabled: true
      keywords: ["AI engineer", "NLP engineer", "ML researcher", "AI startup"]
      confidence_weight: 0.9
      rate_limit: 50
      cache_ttl: 7200
    yc:
      enabled: true
      batches_to_monitor: ["W25", "S25", "W24"]
      confidence_weight: 1.0
      cache_ttl: 86400
    funding_news:
      enabled: true
      sources: ["techcrunch", "36kr", "crunchbase"]
      confidence_weight: 0.9
      rate_limit: 30
      cache_ttl: 43200
  
  validation_rules:
    min_signal_sources: 3
    min_composite_confidence: 7.0
    temporal_consistency_window: "30 days"
    duplicate_threshold: 0.8

# SPELO Scoring System Configuration
spelo_scoring:
  methodology: "SPELO v4.1 - 7 Dimension Investment Assessment"
  dimensions:
    strategy:
      weight: 0.15
      description: "商业模式清晰度、市场定位、竞争策略"
    product:
      weight: 0.15
      description: "产品成熟度、技术壁垒、用户体验"
    execution:
      weight: 0.15
      description: "团队执行力、发展速度、里程碑完成"
    leadership:
      weight: 0.15
      description: "创始人背景、团队构成、行业经验"
    opportunity:
      weight: 0.15
      description: "市场规模、增长潜力、时机判断"
    mrr:
      weight: 0.25  # Highest weight
      description: "月收入规模、增长率、客户留存"
    investment_fit:
      weight: 0.00  # Calculated separately
      description: "融资需求与投资额度匹配度"
  
  scoring_thresholds:
    strong_buy: 60  # ≥60 points
    buy: 50        # 50-59 points
    hold: 40       # 40-49 points
    pass: 0        # <40 points

# Revenue Sharing Model Configuration
revenue_sharing:
  model_type: "Revenue-Based Financing (RBF)"
  sharing_rate: 0.15  # 15% of monthly revenue
  investment_amount: 500000  # RMB per project
  target_payback_months: 8
  expected_total_return: 1.5  # 1.5x total return
  currency_conversion: "USD to RMB at current rates"

# Risk Assessment Framework
risk_assessment:
  risk_categories:
    - technology_risk
    - market_risk  
    - team_risk
    - financial_risk
    - regulatory_risk
  risk_levels: ["Low", "Medium", "High", "Very High"]
  risk_scoring: "1-10 scale per category"

# Authenticity Verification Configuration
authenticity_verification:
  required_checks:
    - github_repository_check
    - product_accessibility_check
    - team_profile_verification
    - business_registration_check
  optional_checks:
    - funding_claim_verification
    - customer_reference_check
    - media_coverage_verification
  verification_threshold: 0.7  # 70% pass rate required

# Quality Assurance Configuration
qa:
  qaLocation: docs/qa
  qaTemplates: .claude/bmad-core/templates/investment-qa-gate-tmpl.yaml
  checklists: .claude/bmad-core/checklists
  review_requirements:
    multi_signal_verification: mandatory
    authenticity_confirmation: mandatory
    spelo_scoring_complete: mandatory
    risk_assessment_complete: mandatory

# Investment Reports Configuration
reports:
  reportLocation: outputs/reports
  reportTemplates: .claude/bmad-core/templates/investment-report-template.yaml
  reportFormats: ["yaml", "markdown", "json"]
  reportRetention: 365  # days
  includeRawData: false
  compressOldReports: true

# Agent Team Configuration for Investment Analysis
agent_teams:
  enabled: true
  config_location: .claude/bmad-core/agent-teams
  default_team: investment-analysis-team
  available_teams:
    - investment-analysis-team
    - discovery-verification-team
    - risk-assessment-team

# Workflow Configuration for Investment Process
workflows:
  enabled: true
  location: .claude/bmad-core/workflows
  default_workflow: ai-startup-investment-analysis
  available_workflows:
    - ai-startup-investment-analysis
    - multi-signal-discovery-only
    - spelo-scoring-only
    - portfolio-review-analysis
    - market-intelligence-gathering

# Search Enhancement for AI Startup Discovery
search:
  concurrent_enabled: true
  default_concurrency: high
  mcp_integration:
    - tavily_search
    - jina_reader
    - github_search
    - funding_database_crawler
  quality_threshold: 8.0  # Higher for investment decisions
  verification_sources: 4   # Require 4 sources for investment-grade data

# Data and Knowledge Base Configuration
knowledge_base:
  location: .claude/bmad-core/data
  investment_kb_files:
    - ai-startup-investment-kb.md
    - spelo-scoring-methodology.md
    - multi-signal-discovery-patterns.md
    - revenue-sharing-benchmarks.md
    - risk-assessment-framework.md
    - authenticity-verification-methods.md

# Performance Monitoring
monitoring:
  track_discovery_performance: true
  track_investment_outcomes: true
  track_revenue_sharing_performance: true
  performance_metrics:
    - discovery_accuracy_rate
    - authenticity_verification_success_rate
    - spelo_prediction_accuracy
    - investment_payback_performance
    - portfolio_roi_tracking

# Integration Settings for Investment Platform
integration:
  with_claude_code: true
  native_subagents: true
  mcp_servers: true
  hook_automation: true
  external_data_sources:
    - crunchbase_api
    - linkedin_sales_navigator
    - twitter_api
    - yc_database
  financial_data_integration: true

# Investment Methodology Configuration
investment_methodology:
  enabled: true
  name: "PocketCorn Multi-Signal Investment Methodology"
  description: "基于多信号交叉验证的AI初创投资决策方法论"
  
  # 4-Round Investment Analysis Cycle
  analysis_cycle:
    round_1_discovery:
      agent: po-investment-analyst
      purpose: "Multi-signal project discovery and initial screening"
      output_type: "discovery_results"
      success_criteria: "3-10 validated projects with 80%+ authenticity rate"
      
    round_2_verification:
      agent: verification-specialist
      purpose: "Comprehensive authenticity verification and data validation"
      output_type: "verification_report"
      success_criteria: "100% authentic projects, detailed verification evidence"
      
    round_3_analysis:
      agent: investment-analyst
      purpose: "SPELO scoring, risk assessment, financial modeling"
      output_type: "investment_analysis"
      success_criteria: "Complete SPELO scores, risk profiles, ROI projections"
      
    round_4_decision:
      agent: investment-decision-maker
      purpose: "Final investment recommendation with terms and conditions"
      output_type: "investment_recommendation"
      success_criteria: "Clear investment decision with supporting rationale"
  
  # Investment Pattern Recognition Framework
  pattern_framework:
    signal_pattern_recognition:
      twitter_patterns: ["product_launch", "founder_announcement", "community_buzz"]
      linkedin_patterns: ["hiring_surge", "team_expansion", "role_descriptions"]
      yc_patterns: ["batch_acceptance", "demo_day_presentation", "alumni_network"]
      funding_patterns: ["round_announcement", "investor_confirmation", "valuation_disclosure"]
      
    authenticity_patterns:
      positive_signals: ["github_activity", "product_demos", "customer_testimonials"]
      red_flags: ["inactive_repos", "broken_product_links", "fake_team_profiles"]
      
    investment_readiness_patterns:
      pmf_indicators: ["revenue_growth", "customer_retention", "market_traction"]
      growth_indicators: ["scaling_team", "expanding_market", "partnership_deals"]
  
  # Quality Assurance for Investment Decisions
  quality_assurance:
    investment_decision_gates:
      - discovery_quality_gate
      - authenticity_verification_gate  
      - spelo_scoring_quality_gate
      - risk_assessment_completion_gate
      - financial_modeling_accuracy_gate
    
    success_metrics:
      discovery_accuracy: ">80%"
      authenticity_rate: "100%"
      spelo_prediction_correlation: ">70%"
      investment_payback_success: ">60%"