version: '3.8'

services:
  scraperr-pocketcorn:
    build: .
    container_name: scraperr-early-stage-finder
    environment:
      - POCKETCORN_TARGET_MRR=50000
      - SCRAPERR_MODE=production
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/app/data
      - ./results:/app/results
    restart: unless-stopped
    networks:
      - scraperr-network

  # 可选：数据库服务
  scraperr-db:
    image: sqlite:latest
    container_name: scraperr-database
    volumes:
      - ./data:/data
    networks:
      - scraperr-network

networks:
  scraperr-network:
    driver: bridge

volumes:
  scraperr-data:
  scraperr-results: